# Generated by Django 4.2.4 on 2023-08-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Flask', 'Flask'), ('Django', 'Django'), ('React.js', 'React.js'), ('Cybersecurity', 'Cybersecurity'), ('Algorithms', 'Algorithms'), ('Data Structures', 'Data Structures'), ('CTF', 'CTF'), ('Web', 'Web')], default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('image_path', models.CharField(max_length=64)),
                ('in_progress', models.BooleanField(default=True)),
                ('badges', models.ManyToManyField(related_name='projects', to='website.badge')),
            ],
        ),
    ]
