# Generated by Django 4.2.4 on 2023-08-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('SQL', 'SQL'), ('Flask', 'Flask'), ('Django', 'Django'), ('React.js', 'React.js'), ('Cybersecurity', 'Cybersecurity'), ('Algorithms', 'Algorithms'), ('Data Structures', 'Data Structures'), ('Competitive Programming', 'Competitive Programming'), ('CTF', 'CTF'), ('Web', 'Web'), ('CS50', 'CS50')], default=None, max_length=32),
        ),
    ]
