# Generated by Django 4.2.4 on 2023-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_project_link_alter_badge_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='badges',
            field=models.ManyToManyField(default=None, related_name='projects', to='website.badge'),
        ),
    ]
