# Generated by Django 4.2.4 on 2023-08-31 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_project_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('SQL', 'SQL'), ('PHP', 'PHP'), ('Flask', 'Flask'), ('Django', 'Django'), ('React.js', 'React.js'), ('Cybersecurity', 'Cybersecurity'), ('Algorithms', 'Algorithms'), ('Data Structures', 'Data Structures'), ('Competitive Programming', 'Competitive Programming'), ('CTF', 'CTF'), ('Web', 'Web'), ('CS50', 'CS50'), ('AI', 'AI'), ('GUI', 'GUI'), ('BOT', 'BOT')], default=None, max_length=32),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('display_name', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('depth', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='website.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('content', models.TextField(max_length=2147483648)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=64)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.ManyToManyField(related_name='blogs', to='website.comment')),
            ],
        ),
    ]
