# Generated by Django 4.2.4 on 2023-08-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_badge_badge_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=2147483647),
        ),
    ]
