# Generated by Django 4.2.4 on 2023-08-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='depth',
        ),
    ]
