# Generated by Django 4.2.4 on 2023-08-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
