# Generated by Django 4.2.4 on 2023-09-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_blog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='approx_length_min',
            field=models.IntegerField(default=5),
        ),
    ]
