# Generated by Django 4.2.4 on 2023-09-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
