# Generated by Django 4.2.4 on 2023-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_badge_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, related_name='blogs', to='website.comment'),
        ),
    ]
